CREATE TABLE USUARIO (
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(250),
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(250) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
);