CREATE TABLE DEPARTAMENTO (
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    COR VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
);
