CREATE TABLE TAREFA (
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(250),
    STATUS VARCHAR(20) NOT NULL,
    DEPARTAMENTO_ID VARCHAR(36) NOT NULL,
    CRIADOR_ID VARCHAR(36) NOT NULL,
    RESPONSAVEL_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),

    CONSTRAINT FK_TAREFA_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TAREFA_CRIADOR FOREIGN KEY (CRIADOR_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TAREFA_RESPONSAVEL FOREIGN KEY (RESPONSAVEL_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE
);
